#!/usr/bin/env bash

python_files=()

while IFS= read -r file; do
    python_files+=("$file")
done < <(find . -type d -name .git -prune -o -type f -name "*.py" -print)

while IFS= read -r file; do
    mime=$(file -b --mime-type "$file")
    if [ "$mime" = 'text/x-python' ] || [ "$mime" = 'text/x-script.python' ]; then
        python_files+=("$file")
    fi
done < <(find . -type f ! -name "*.*")

for file in "${python_files[@]}"; do
    if [ -n "$WB_PYTHON_FILES_EXCLUDE" ] && echo "$file" | grep -q "$WB_PYTHON_FILES_EXCLUDE"; then
        continue
    fi
    echo "$file"
done
